name: Playwright Tests

# Когда запускать workflow
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
env:
  BASE_URL: https://conduit-realworld-example-app.fly.dev
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_PASS: ${{ secrets.USER_PASS }}

jobs:
  test:
    runs-on: macos-latest # macOS runner, подойдет для MacBook

    steps:
      # 1️⃣ Забираем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Устанавливаем браузеры Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5️⃣ Запуск тестов
      - name: Run Playwright tests
        run: npm test

      # 6️⃣ Сохраняем отчёт (HTML + скриншоты)
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
